import com.scalakata._

@instrument class Index {
md"""|1. [encoding/decoding with scodec](/0_scodec.scala)
     |1. ...
     |1. ...
     |1. ...
     |1. ...
     |1. ...
     |1. ...
     |1. ...""".stripMargin.fold
}